INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (1, 'Napa', 'USA', 'Ackerman', 'CA');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (2, 'Woodinville', 'USA', 'aMaurice', 'WA');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (3, 'Woodinville', 'USA', 'Andrew Will', 'WA');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (4, 'Seattle', 'USA', 'ANW', 'WA');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (5, 'Woodinville', 'USA', 'Betz', 'WA');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (6, 'Tumwater', 'USA', 'Bordeaux Wine Locators', 'WA');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (7, 'Seattle', 'USA', 'C & G`', 'WA');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (8, 'Seattle', 'USA', 'Cadence', 'WA');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (9, 'Online', 'Online', 'CellaRaiders', 'Online');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (10, 'Bellevue', 'USA', 'Chuck', 'WA');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (11, 'Concon', 'Chile', 'Click', 'Valparaiso');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (12, 'Seattle', 'USA', 'Columbia', 'WA');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (13, 'Woodinville', 'USA', 'Cru Selections', 'WA');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (14, 'Woodinville', 'USA', 'Delille', 'WA');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (15, 'Various', 'Various', 'Direct Distributed', 'Various');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (16, 'Seattle', 'USA', 'Elliot Bay', 'WA');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (17, 'Seattle', 'USA', 'Full Pull', 'WA');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (18, 'Southwick', 'UK', 'GM Drinks', 'Hampshire');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (19, 'Portland', 'USA', 'Grape Expectations', 'OR');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (20, 'New York', 'USA', 'Indie', 'NY');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (22, 'Walla Walla', 'USA', 'Mark Ryan', 'WA');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (23, 'Kent', 'USA', 'Moda', 'WA');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (24, 'Richmond', 'USA', 'Winebow', 'VA');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (25, 'Tuscon', 'USA', 'Cordon', 'AZ');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (26, 'Kent', 'USA', 'Prime Wine and Spirits', 'WA');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (27, 'Bellevue', 'USA', 'Seastar', 'WA');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (28, 'Bellevue', 'USA', 'Southern Wine and Spirits', 'WA');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (29, 'Seattle', 'USA', 'Cavatappi', 'WA');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (30, 'Bellingham', 'USA', 'Evergreen', 'WA');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (31, 'Southbury', 'USA', 'Wine Trust', 'CT');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (32, 'Woodinville', 'USA', 'Two Vintners', 'WA');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (33, 'Renton', 'USA', 'Unique Wine Co', 'WA');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (34, 'Kent', 'USA', 'Vehrs', 'WA');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (35, 'Seattle', 'USA', 'Vinum', 'WA');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (36, 'New York', 'USA', 'Walden Wine and Spirits', 'NY');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (37, 'Auburn', 'USA', 'Young''s', 'WA');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (38, 'Bellevue', 'USA', 'Vin2U', 'WA');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (39, 'Seattle', 'USA', 'Vinea', 'WA');
INSERT INTO cybersomm.vendor (id, city, country, name, state) VALUES (96, 'Woodinville', 'USA', 'Andrew Will', 'CO');